// Prestige Properties — Data

const LISTINGS = [
  {
    id: 1, status: "For Sale", price: "€1,250,000",
    title: "4-bed Victorian Townhouse", address: "Pembroke Road, Ballsbridge, Dublin 4",
    beds: 4, baths: 3, sqm: 245, tags: ["Period", "Garden", "Garage"],
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    description: "An immaculately restored Victorian on one of Ballsbridge's most sought-after streets. South-facing rear garden, original cornice work, two reception rooms, and a kitchen extension by Niall McLaughlin.",
    agent: "Sophia Kavanagh", area: "Ballsbridge",
  },
  {
    id: 2, status: "For Sale", price: "€495,000",
    title: "Modern 2-bed Apartment", address: "Grand Canal Dock, Dublin 2",
    beds: 2, baths: 2, sqm: 92, tags: ["New", "Balcony", "Concierge"],
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    description: "Bright corner apartment with floor-to-ceiling glazing onto the Liffey. Underfloor heating, concierge, secure parking, and a private balcony with quay views.",
    agent: "Sophia Kavanagh", area: "Grand Canal Dock",
  },
  {
    id: 3, status: "For Sale", price: "€785,000",
    title: "3-bed Semi-Detached", address: "Ranelagh, Dublin 6",
    beds: 3, baths: 2, sqm: 156, tags: ["Renovated", "South-facing"],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
    description: "A handsome semi in the heart of Ranelagh, freshly renovated with a Plain English kitchen, refinished pitch-pine floors, and a walled south-facing garden.",
    agent: "Sophia Kavanagh", area: "Ranelagh",
  },
  {
    id: 4, status: "For Sale", price: "€1,850,000",
    title: "Penthouse with Liffey Views", address: "Hanover Quay, Dublin 2",
    beds: 3, baths: 3, sqm: 210, tags: ["Penthouse", "Terrace", "Lift"],
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
    description: "Top-floor duplex with a 60sqm wraparound terrace and direct lift access. Sweeping Liffey and Poolbeg views, double-height living, and a media room with custom joinery.",
    agent: "Sophia Kavanagh", area: "Grand Canal Dock",
  },
  {
    id: 5, status: "For Rent", price: "€2,800/mo",
    title: "Sandymount Coastal Cottage", address: "Strand Road, Sandymount, Dublin 4",
    beds: 2, baths: 1, sqm: 88, tags: ["Furnished", "Sea Views"],
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80",
    description: "A characterful coastal cottage moments from Sandymount Strand. Fully furnished to a high standard, with a south-facing courtyard and uninterrupted sea-facing aspect.",
    agent: "Sophia Kavanagh", area: "Sandymount",
  },
  {
    id: 6, status: "For Sale", price: "€945,000",
    title: "New-build 4-bed Detached", address: "Dundrum, Dublin 14",
    beds: 4, baths: 3, sqm: 198, tags: ["A-Rated", "EV Charger", "Garden"],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    description: "Brand-new A-rated detached home in a quiet Dundrum cul-de-sac. Triple glazing, air-source heating, EV charger, fully landscaped garden, and a 10-year structural guarantee.",
    agent: "Sophia Kavanagh", area: "Dundrum",
  },
  {
    id: 7, status: "For Sale", price: "€1,150,000",
    title: "Georgian Mews House", address: "Fitzwilliam Lane, Dublin 2",
    beds: 3, baths: 2, sqm: 175, tags: ["Mews", "Period", "Parking"],
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    description: "A beautifully converted Georgian mews tucked behind Fitzwilliam Square. Exposed brick, original cobblestone courtyard, and a roof terrace with Georgian Dublin roofscape views.",
    agent: "Sophia Kavanagh", area: "Ballsbridge",
  },
  {
    id: 8, status: "For Rent", price: "€1,450/mo",
    title: "Bright Studio Apartment", address: "Smithfield, Dublin 7",
    beds: 1, baths: 1, sqm: 48, tags: ["Furnished", "Balcony", "Gym"],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    description: "Compact and clever studio with a private balcony overlooking Smithfield Square. Residents' gym, concierge, and roof terrace. Minutes from the Luas Red Line.",
    agent: "Sophia Kavanagh", area: "Smithfield",
  },
  {
    id: 9, status: "For Sale", price: "€620,000",
    title: "3-bed Victorian Terrace", address: "Portobello, Dublin 8",
    beds: 3, baths: 2, sqm: 138, tags: ["Period", "Canal Views"],
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=1200&q=80",
    description: "A well-maintained red-brick Victorian terrace steps from the Grand Canal. Original fireplaces, high ceilings, and a private rear garden with westerly aspect.",
    agent: "Sophia Kavanagh", area: "Portobello",
  },
  {
    id: 10, status: "For Sale", price: "€2,200,000",
    title: "5-bed Detached Residence", address: "Westminster Road, Foxrock, Dublin 18",
    beds: 5, baths: 4, sqm: 390, tags: ["Detached", "Pool", "Wine Cellar"],
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    description: "A statement family home in Foxrock's most prestigious enclave. Heated outdoor pool, home cinema, wine cellar, and a mature 0.4-acre garden landscaped by Dermot Fogarty.",
    agent: "Sophia Kavanagh", area: "Foxrock",
  },
  {
    id: 11, status: "For Sale", price: "€395,000",
    title: "2-bed Sea-View Duplex", address: "Harbour Road, Dún Laoghaire",
    beds: 2, baths: 2, sqm: 98, tags: ["Sea Views", "Duplex", "Parking"],
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    description: "Split-level duplex with direct harbour and sea views from the main living area. Private balcony, two allocated parking spaces, and a short walk to the Dart.",
    agent: "Sophia Kavanagh", area: "Dún Laoghaire",
  },
  {
    id: 12, status: "For Rent", price: "€3,500/mo",
    title: "Period Apartment, Merrion Square", address: "Merrion Square East, Dublin 2",
    beds: 2, baths: 1, sqm: 118, tags: ["Period", "Furnished", "Unfurnished option"],
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
    description: "First-floor apartment in a restored Georgian on Dublin's finest square. Original cornice, shuttered windows, working fireplace, and a private mews parking space included.",
    agent: "Sophia Kavanagh", area: "Ballsbridge",
  },
  {
    id: 13, status: "For Sale", price: "€875,000",
    title: "4-bed Semi-Detached", address: "Castle Avenue, Clontarf, Dublin 3",
    beds: 4, baths: 3, sqm: 182, tags: ["Renovated", "Garden", "Near DART"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    description: "Extensively renovated semi on one of Clontarf's most desirable roads. Open-plan kitchen-dining with bi-fold doors to a 90sqm south-facing garden, and a converted attic study.",
    agent: "Sophia Kavanagh", area: "Clontarf",
  },
  {
    id: 14, status: "For Rent", price: "€1,700/mo",
    title: "Temple Bar Pied-à-Terre", address: "Cecilia Street, Temple Bar, Dublin 2",
    beds: 1, baths: 1, sqm: 54, tags: ["City Centre", "Furnished"],
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    description: "Compact one-bed with a city-centre address and excellent finish. Stone's throw from the Cultural Quarter, Government Buildings, and every amenity Dublin 2 offers.",
    agent: "Sophia Kavanagh", area: "Smithfield",
  },
  {
    id: 15, status: "For Sale", price: "€740,000",
    title: "3-bed Extended Bungalow", address: "Stillorgan Road, Stillorgan, Dublin 18",
    beds: 3, baths: 2, sqm: 168, tags: ["Bungalow", "Garden", "Garage"],
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    description: "A generously extended single-storey home with a corner plot garden and double garage. Ideal for downsizers or those seeking single-level living in a mature, quiet setting.",
    agent: "Sophia Kavanagh", area: "Dundrum",
  },
  {
    id: 16, status: "For Sale", price: "€1,320,000",
    title: "Sky Penthouse", address: "D'Olier Street, Dublin 2",
    beds: 3, baths: 2, sqm: 195, tags: ["Penthouse", "City Views", "Concierge"],
    image: "https://images.unsplash.com/photo-1616137466211-f939a420be84?auto=format&fit=crop&w=1200&q=80",
    description: "Spectacular top-floor residence with 270° city views from a wraparound terrace. Custom interiors by Kennedy Nolan, smart home throughout, and 24-hour concierge.",
    agent: "Sophia Kavanagh", area: "Grand Canal Dock",
  },
  {
    id: 17, status: "For Rent", price: "€2,200/mo",
    title: "Artisan Cottage", address: "Manor Street, Stoneybatter, Dublin 7",
    beds: 2, baths: 1, sqm: 82, tags: ["Character", "Garden", "Unfurnished"],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    description: "A red-brick artisan cottage with original features and a private rear garden. Newly decorated, double-glazed, and in one of Dublin 7's most vibrant and walkable neighbourhoods.",
    agent: "Sophia Kavanagh", area: "Smithfield",
  },
  {
    id: 18, status: "For Sale", price: "€1,780,000",
    title: "5-bed Victorian Residence", address: "Dartry Road, Dartry, Dublin 6",
    beds: 5, baths: 4, sqm: 340, tags: ["Period", "Double-fronted", "Off-market"],
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    description: "A magnificent double-fronted Victorian with five bedrooms, four bathrooms, and a 180sqm living footprint across four reception rooms. Recently insulated and re-roofed.",
    agent: "Sophia Kavanagh", area: "Ranelagh",
  },
  {
    id: 19, status: "For Sale", price: "€565,000",
    title: "New-build 3-bed Mid-Terrace", address: "Santry Cross, Santry, Dublin 9",
    beds: 3, baths: 2, sqm: 125, tags: ["A-Rated", "New Build", "EV Charger"],
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
    description: "Contemporary mid-terrace in a new Santry development with an A2 energy rating, solar panels, and EV charger. Bright open-plan living, three double bedrooms, and a private rear garden.",
    agent: "Sophia Kavanagh", area: "Clontarf",
  },
  {
    id: 20, status: "For Sale", price: "€425,000",
    title: "Garden-Level Apartment", address: "Rathmines Road Upper, Rathmines, Dublin 6",
    beds: 2, baths: 1, sqm: 86, tags: ["Garden Access", "Period Building", "Parking"],
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80",
    description: "Lower-ground apartment in a handsome Victorian red-brick with exclusive use of a private south-facing garden. Tastefully modernised while retaining original ceiling height and cornicing.",
    agent: "Sophia Kavanagh", area: "Ranelagh",
  },
  {
    id: 21, status: "For Sale", price: "€3,100,000",
    title: "Manor House on 0.8 Acres", address: "Killiney Hill Road, Killiney, Dublin 18",
    beds: 6, baths: 5, sqm: 520, tags: ["Sea Views", "Pool", "Gate Lodge"],
    image: "https://images.unsplash.com/photo-1571055107559-3e67626fa8be?auto=format&fit=crop&w=1200&q=80",
    description: "An exceptional south Co. Dublin residence on 0.8 acres with panoramic sea and Bray Head views. Principal suite with dressing room, a heated pool, games room, and two-bedroom gate lodge.",
    agent: "Sophia Kavanagh", area: "Foxrock",
  },
  {
    id: 22, status: "For Rent", price: "€2,450/mo",
    title: "IFSC 2-bed Apartment", address: "Mayor Street Lower, IFSC, Dublin 1",
    beds: 2, baths: 2, sqm: 94, tags: ["Furnished", "Concierge", "River Views"],
    image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
    description: "Contemporary two-bed in the International Financial Services Centre. River Liffey views, residents' concierge and gym, underground parking, and immediate proximity to financial district employers.",
    agent: "Sophia Kavanagh", area: "Grand Canal Dock",
  },
  {
    id: 23, status: "For Sale", price: "€890,000",
    title: "Converted Warehouse Loft", address: "Grand Canal Street Lower, Dublin 4",
    beds: 2, baths: 2, sqm: 178, tags: ["Loft", "Industrial", "Unique"],
    image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80",
    description: "A genuinely one-of-a-kind industrial conversion with 4.5m ceilings, exposed steel I-beams, and polished concrete floors. Mezzanine bedroom, roof terrace, and two secure parking spaces.",
    agent: "Sophia Kavanagh", area: "Grand Canal Dock",
  },
  {
    id: 24, status: "For Sale", price: "€695,000",
    title: "3-bed End-of-Terrace", address: "Harold's Cross Road, Harold's Cross, Dublin 6W",
    beds: 3, baths: 2, sqm: 147, tags: ["Corner Plot", "Garden", "Parking"],
    image: "https://images.unsplash.com/photo-1447767879228-3b55c084bcdb?auto=format&fit=crop&w=1200&q=80",
    description: "Attractive end-of-terrace with a side garden and off-street parking. Thoughtfully extended to the rear, with underfloor heating, a new kitchen, and a converted attic room.",
    agent: "Sophia Kavanagh", area: "Portobello",
  },
];

const TESTIMONIALS = [
  { rating: 5, quote: "Sophia found us a home we didn't even know to look for. Her eye for what suits a family is uncanny — and the off-market access was decisive.", name: "Eoin & Maeve Doherty", detail: "Bought in Ranelagh · 2025" },
  { rating: 5, quote: "Sold above asking in nine days. The styling advice, the photography, the way viewings were curated — every detail felt considered.", name: "Aisling N.", detail: "Sold in Dublin 2 · 2025" },
  { rating: 5, quote: "We were relocating from London with two weeks' notice. Sophia handled viewings by video, then keys on arrival. Faultless.", name: "James Whitford", detail: "Rented in Sandymount · 2024" },
  { rating: 5, quote: "The off-market introduction saved us months of searching. Sophia knew exactly what we needed before we did.", name: "Ciarán & Ruth Molloy", detail: "Bought in Ballsbridge · 2025" },
  { rating: 5, quote: "Professional, calm, and genuinely invested in the outcome. We achieved 12% above guide price. Remarkable.", name: "Patricia Healy", detail: "Sold in Foxrock · 2024" },
  { rating: 5, quote: "First-time buyers and completely out of our depth. Sophia walked us through everything. We never felt like a small deal.", name: "Declan O'Brien", detail: "Bought in Portobello · 2025" },
];

const STATS = [
  { value: 340, suffix: "+", label: "Homes Sold" },
  { value: 14, suffix: "", label: "Years Experience" },
  { value: 98, suffix: "%", label: "Client Satisfaction" },
  { value: 12, suffix: "", label: "Avg Days to Sell" },
];

const MARQUEE_ITEMS = [
  "340+ Homes Sold", "Dublin 2", "Dublin 4", "Free Valuations",
  "WhatsApp Support", "Off-Market Access", "Luxury Residential",
];

const CHAT_SCRIPT = [
  { from: "agent", text: "Hi, I'm Sophia. Looking for a particular neighbourhood or budget?" },
  { from: "user", text: "Something in Dublin 4, around €1.2M, 3+ beds." },
  { from: "agent", text: "Perfect — I have two off-market in Ballsbridge that match. Want me to send details?" },
];

const BLOG_POSTS = [
  {
    slug: "buying-in-dublin-4",
    title: "5 Things to Know Before Buying in Dublin 4",
    excerpt: "From Ballsbridge to Sandymount, Dublin 4 commands a premium. Here's what every buyer should understand before entering this market.",
    date: "12 May 2026", readTime: "4 min read", category: "Buying Guide",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    content: [
      { heading: "Location is everything — and so is micro-location", body: "Dublin 4 spans a wide range of character. Ballsbridge is embassy belt and Georgian grandeur. Sandymount is coastal and quiet. Donnybrook is village-like and convenient. Before you view a single property, decide which micro-location suits your lifestyle — commute, schools, weekend rhythm." },
      { heading: "Off-market is how the best homes trade", body: "A significant portion of Dublin 4 transactions never appear on MyHome or Daft. Vendors at this price point value discretion. Working with an agent who has deep local relationships is less a luxury than a practical necessity if you want genuine access to the market." },
      { heading: "Condition surveys are non-negotiable on period homes", body: "Victorian and Edwardian properties are beautiful and often poorly maintained beneath the surface. Commission a full structural survey before bidding. Drainage, roof timbers, damp, and original sash windows all have meaningful costs when they need attention." },
      { heading: "Bidding moves fast — be financially ready", body: "Good properties in Dublin 4 attract multiple bidders within days. Have your mortgage approval in principle ready, know your absolute ceiling, and appoint a solicitor in advance. Hesitation is expensive when competing in this market." },
      { heading: "Think about the exit before you buy", body: "Consider the resale profile of what you're buying. A four-bedroom with a south-facing garden in Ballsbridge is highly liquid. A one-bedroom in a large apartment block is harder. Buy what suits your life, but understand the resale implications from day one." },
    ],
  },
  {
    slug: "off-market-advantage",
    title: "The Off-Market Advantage: Dublin's Hidden Listings",
    excerpt: "Most buyers never see the properties that matter most. Here's how off-market access works — and why it changes everything.",
    date: "28 Apr 2026", readTime: "5 min read", category: "Market Insight",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    content: [
      { heading: "What off-market actually means", body: "Off-market simply means a property is for sale but not publicly advertised on portals. The vendor has chosen to sell quietly — to avoid disruption, protect privacy, or reach a specific buyer profile. These transactions are common at the premium end of the Dublin market." },
      { heading: "Why vendors choose this route", body: "Discretion is the primary driver. Senior executives, public figures, and families going through life transitions often prefer a sale handled without public viewings, photographs online, or neighbours knowing the asking price. The right agent makes this possible while still achieving full market value." },
      { heading: "How buyers gain access", body: "Off-market access comes through relationships, not portals. Vendors share details with agents they trust. Those agents share with qualified buyers on their books. The key is being registered with an active agent, financially prepared, and clear about what you want." },
      { heading: "What you get as a buyer", body: "Less competition, more time to think, and often a more straightforward negotiation. Without a public bidding war, both parties can reach a considered outcome. You may secure something exceptional before anyone else even knows it exists." },
    ],
  },
  {
    slug: "ranelagh-vs-ballsbridge",
    title: "Ranelagh vs Ballsbridge: Which is Right for You?",
    excerpt: "Two of Dublin's most sought-after neighbourhoods — both excellent, but very different. A clear-headed comparison for buyers.",
    date: "15 Apr 2026", readTime: "6 min read", category: "Neighbourhood Guide",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
    content: [
      { heading: "The character difference", body: "Ranelagh is a working village — cafes, restaurants, a Luas stop, a mix of young families and long-established residents. Ballsbridge is quieter, more formal, with embassies, RDS grounds, and period houses set back from wider roads. Both are premium. The atmosphere is distinct." },
      { heading: "What you get for your money", body: "Ranelagh offers more variety at lower price points. A three-bedroom terraced house typically runs €650,000–€850,000. In Ballsbridge, a similar specification in a detached Victorian commands €1.2M+. The premium reflects the address as much as the bricks." },
      { heading: "Schools and families", body: "Both areas have excellent primary and secondary school options. Ballsbridge has a slight edge in terms of private school proximity. Ranelagh has a broader mix of community schools that many families prefer for the village atmosphere." },
      { heading: "Transport and access", body: "Ranelagh wins on public transport — the Luas Green Line connects it directly to the city in minutes. Ballsbridge is walkable to Baggot Street and has good bus links, but no Luas. If daily commuting by public transport matters, Ranelagh has a practical edge." },
    ],
  },
  {
    slug: "prepare-home-for-sale",
    title: "How to Prepare Your Home for a Successful Sale",
    excerpt: "First impressions determine offers. A practical checklist for sellers who want to achieve the best price in the shortest time.",
    date: "3 Apr 2026", readTime: "5 min read", category: "Selling Guide",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    content: [
      { heading: "Declutter before anything else", body: "Every item that doesn't belong in a show home should go into storage. Buyers need to imagine their lives in the space. Personal collections, excess furniture, and storage overflow all shrink rooms and distract from the property's bones." },
      { heading: "Address the snag list honestly", body: "Walk through the property with fresh eyes. Cracked tiles, dripping taps, peeling paint — these are small costs that read as big problems to buyers. A pre-sale snag resolved is worth multiples of its repair cost in buyer confidence." },
      { heading: "Presentation photography is not optional", body: "Your photographs are your property's first showing. They determine whether a buyer books a viewing or scrolls past. Invest in a photographer who specialises in residential property. The difference in results is significant." },
      { heading: "Time the market thoughtfully", body: "Spring (March–May) and autumn (September–November) are traditionally the strongest selling seasons in Dublin. Summer is slow. If your property isn't ready for a spring launch, it is almost always better to wait for autumn than to list in August." },
    ],
  },
  {
    slug: "dublin-property-market-2026",
    title: "Dublin Property Market: Spring 2026 Report",
    excerpt: "Supply remains constrained. Demand is steady. Here's what the numbers and on-the-ground reality say about the market right now.",
    date: "20 Mar 2026", readTime: "7 min read", category: "Market Report",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    content: [
      { heading: "Supply: still the defining issue", body: "The fundamental constraint on the Dublin market remains the same as it has for a decade: not enough homes. Planning permission volumes improved in 2025, but completions continue to lag well behind household formation. Competition on well-presented properties will not ease materially this year." },
      { heading: "Pricing: stable at the premium end", body: "Properties above €800,000 have shown price stability through Q1 2026. The mid-market (€400K–€700K) saw modest appreciation of 3–4% year-on-year. First-time buyer stock below €400K remains acutely undersupplied and aggressively bid." },
      { heading: "Interest rates: less of a headwind", body: "ECB rate stabilisation through late 2025 has had a measurable effect on buyer confidence. Fixed-rate mortgage products in the 3.2–3.8% range are widely available. Monthly repayments that looked difficult 18 months ago are now more accessible for buyers with adequate deposits." },
      { heading: "What we're seeing on the ground", body: "Well-priced, well-presented properties in core locations continue to attract multiple bids within two weeks of launch. Vendors who invest in professional styling and photography are consistently achieving 5–8% above guide. Those who don't are watching their properties sit." },
    ],
  },
  {
    slug: "first-time-buyer-guide",
    title: "First-Time Buyer's Guide to Dublin",
    excerpt: "The process can feel overwhelming. It doesn't have to be. A plain-English walkthrough of buying your first home in Dublin.",
    date: "8 Mar 2026", readTime: "8 min read", category: "Buying Guide",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    content: [
      { heading: "Step 1: Get your mortgage approval in principle", body: "Before viewing a single property, meet with a mortgage broker. An approval in principle (AIP) tells you exactly what you can borrow, and makes you a credible buyer when you bid. Without it, most serious vendors won't engage." },
      { heading: "Step 2: Understand what you're buying", body: "New build or second-hand? Apartment or house? Each comes with different considerations. New builds offer A-rated energy efficiency and low maintenance; second-hand homes offer character and often better locations. Know what you're choosing." },
      { heading: "Step 3: The bidding process", body: "In Ireland, bidding is done verbally through the selling agent. There is no formal legal obligation until contracts are exchanged. Bid at what you can genuinely afford. Know your absolute ceiling before you start." },
      { heading: "Step 4: Appoint a solicitor early", body: "You'll need a conveyancing solicitor before you go sale agreed. They'll review the contract, title deeds, planning permissions, and management company accounts if applicable. A good solicitor catches problems early. A slow one costs you the sale." },
    ],
  },
];

const NEIGHBORHOODS = [
  {
    id: "ballsbridge",
    name: "Ballsbridge",
    district: "Dublin 4",
    tagline: "Dublin's embassy quarter — period grandeur, quiet streets",
    description: "Ballsbridge is Dublin's most prestigious address. Home to embassies, the RDS, Aviva Stadium, and some of the finest Victorian and Edwardian housing stock in the country. Wide, tree-lined roads, excellent schools, and a 15-minute walk to St Stephen's Green define this neighbourhood.",
    avgSale: "€1.2M+",
    type: "Houses & Apartments",
    highlights: ["RDS Arena", "Embassy Belt", "Aviva Stadium", "Dart Access"],
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "ranelagh",
    name: "Ranelagh",
    district: "Dublin 6",
    tagline: "Village atmosphere, Luas access, young and established families",
    description: "Ranelagh is the archetype of the Dublin village suburb — independent restaurants, Saturday markets, a strong community, and the Luas Green Line threading through it. Period red-brick terraces sit beside new builds. Consistently popular with young professionals and families alike.",
    avgSale: "€700K–€900K",
    type: "Houses & Period Apartments",
    highlights: ["Luas Green Line", "Village High Street", "Beechwood Park", "Strong Schools"],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "grand-canal-dock",
    name: "Grand Canal Dock",
    district: "Dublin 2 & 4",
    tagline: "Tech hub, waterside living, modern architecture",
    description: "The heartbeat of Dublin's tech corridor. Google, Airbnb, LinkedIn, and Meta have all planted significant offices here. The result is a neighbourhood of high-spec apartments, excellent restaurants, and a canal basin that becomes Dublin's gathering point in summer.",
    avgSale: "€500K–€1.8M",
    type: "Modern Apartments & Penthouses",
    highlights: ["Tech Campus Hub", "Canal Basin", "Bord Gáis Energy Theatre", "DART Access"],
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "sandymount",
    name: "Sandymount",
    district: "Dublin 4",
    tagline: "Coastal village, strand walks, quiet family life",
    description: "Sandymount feels a world apart from the city despite being minutes from it. The coastal village stretches along Sandymount Strand — a 5km tidal beach ideal for morning walks and evening swims. Characterful cottages, period semis, and a genuine community make it one of Dublin's most liveable addresses.",
    avgSale: "€600K–€1.1M",
    type: "Cottages & Semis",
    highlights: ["Sandymount Strand", "Village Centre", "DART Station", "Sea Views"],
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "portobello",
    name: "Portobello",
    district: "Dublin 8",
    tagline: "Canal-side bohemia, period red-bricks, creative energy",
    description: "Portobello has evolved from an overlooked canal-side neighbourhood into one of Dublin's most desirable. Independent coffee shops, brunch spots, and a creative community have taken root alongside the Georgian and Victorian housing stock that lines the Grand Canal.",
    avgSale: "€550K–€800K",
    type: "Victorian Terraces & Apartments",
    highlights: ["Grand Canal", "Portobello Harbour", "Leonard's Corner", "Luas Access"],
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "foxrock",
    name: "Foxrock",
    district: "Dublin 18",
    tagline: "Leafy south Dublin — privacy, space, prestige",
    description: "Foxrock is south Dublin's most private address. Large detached homes on generous plots, mature trees, and a very discreet market define this DART-line village. The area attracts senior executives, returned diaspora, and families who value space and quiet above all.",
    avgSale: "€1.5M–€4M",
    type: "Detached Houses & Estates",
    highlights: ["DART Station", "Foxrock Village", "Mature Gardens", "Top Schools"],
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
  },
];

const SERVICES = [
  {
    icon: "🏡",
    title: "Property Sales",
    subtitle: "Full selling service",
    description: "From valuation to completion, we manage every detail — professional photography, targeted marketing, curated viewings, and hard negotiations on your behalf. Most of our vendors achieve above guide price.",
    cta: "Request a Valuation",
  },
  {
    icon: "🔍",
    title: "Buyer's Agency",
    subtitle: "We find it for you",
    description: "We work exclusively on your side — identifying properties on and off market, accompanying viewings, providing honest advice, and negotiating purchase terms. Clarity and advocacy at every stage.",
    cta: "Start Your Search",
  },
  {
    icon: "📋",
    title: "Lettings & Management",
    subtitle: "Hands-off landlord service",
    description: "Tenant sourcing, referencing, lease management, rent collection, and maintenance coordination. We protect your investment so you don't have to manage it day to day.",
    cta: "Discuss Your Property",
  },
  {
    icon: "📊",
    title: "Private Valuations",
    subtitle: "Confidential & obligation-free",
    description: "Thinking about selling but not ready to commit? A private valuation gives you an honest market assessment with no strings attached and no public record. Completely discreet.",
    cta: "Book a Valuation",
  },
  {
    icon: "🗝️",
    title: "Off-Market Access",
    subtitle: "The invisible listings",
    description: "Registered buyers on our books are the first to hear about properties that never reach public portals. If you're a serious buyer, join our private register and gain access to Dublin's most discreet transactions.",
    cta: "Join the Register",
  },
  {
    icon: "💼",
    title: "Investment Advisory",
    subtitle: "Portfolio strategy & acquisition",
    description: "Yield analysis, area selection, renovation cost modelling, and acquisition support for investors building or optimising a Dublin residential portfolio. Straightforward advice, no jargon.",
    cta: "Talk to Sophia",
  },
];

Object.assign(window, { LISTINGS, TESTIMONIALS, STATS, MARQUEE_ITEMS, CHAT_SCRIPT, BLOG_POSTS, NEIGHBORHOODS, SERVICES });
